--- Nickname pools used to build German villager display names.
local nicknames = {}

nicknames.female = {
    "Schwindlerin",
    "Diebin",
    "Kokette",
    "Hochstaplerin",
    "Schwester",
    "Mutter",
    "Großmutter",
    "Schönheit",
    "Kämpferin",
    "Zofe",
    "Amme",
    "Dienerin",
    "Bäuerin",
    "Dichterin",
    "Kirchendienerin",
    "Näherin",
    "Göttin",
    "Räubertochter",
    "Pfaffentochter",
    "Bauerntochter",
    "Heilfrau",
    "Nonne",
    "Krähe",
    "Lärche",
    "Nachtigall",
    "Jungfrau",
    "Tänzerin",
    "Zauberin",
    "Badefrau",
    "Mütterliche",
    "Kräuterfrau"
}

nicknames.male = {
    "Sonderling",
    "Schwindler",
    "Dieb",
    "Frauenheld",
    "Fels",
    "Baum",
    "Schlächter",
    "Knochenbrecher",
    "Hochstapler",
    "Seemann",
    "Kapitän",
    "Bruder",
    "Vater",
    "Großvater",
    "Aufschneider",
    "Gespaltene",
    "Angeber",
    "Kämpfer",
    "Tölpel",
    "Krüppel",
    "Räuber",
    "Henker",
    "Pfaffe",
    "Dichter",
    "Krieger",
    "Bauernsohn",
    "Pastorensohn",
    "Affenmann",
    "Vogelmann",
    "Pastor",
    "Prediger",
    "Wanderer",
    "Bärtige",
    "Mönch",
    "Bär",
    "Hund",
    "Hengst",
    "Schläger",
    "Säufer",
    "Riese",
    "Tänzer",
    "Stinker",
    "Jüngling",
    "Stotterer",
    "Frömmler",
    "Heiler",
    "Schwachkopf",
    "Dummkopf",
    "Narr",
    "Bader",
    "Bayer",
    "Sachse",
    "Franke",
    "Slave",
    "Schwede",
    "Landstreicher",
    "Tagelöhner",
    "Tunichtgut",
    "Wilderer",
    "Väterliche",
    "Waldläufer",
    "Steiger"
}

nicknames.common = {
    "Tapfere",
    "Furchtlose",
    "Sonderbare",
    "Sonderliche",
    "Schüchterne",
    "Verhärmte",
    "Ehrliche",
    "Feige",
    "Eloquente",
    "Schmierige",
    "Duftende",
    "Ältere",
    "Jüngere",
    "Fromme",
    "Böse",
    "Verrückte",
    "Stille",
    "Falsche",
    "Laute",
    "Barmherzige",
    "Warmherzige",
    "Neidische",
    "Dunkle",
    "Finstere",
    "Beste",
    "Fiese",
    "Starke",
    "Schwache",
    "Schmutzige",
    "Faule",
    "Fleißige",
    "Geniale",
    "Kleine",
    "Große",
    "Reiche",
    "Lange",
    "Kurze",
    "Wilde",
    "Schnelle",
    "Listige",
    "Verständige",
    "Unreine",
    "Verwegene",
    "Traurige",
    "Rastlose",
    "Geplagte",
    "Bucklige",
    "Dumme",
    "Dumpfe",
    "Glückliche",
    "Wanderlustige",
    "Einfältige",
    "Niederträchtige",
    "Fette",
    "Feiste",
    "Dünne",
    "Dürre",
    "Taube",
    "Blinde",
    "Käufliche",
    "Erhabene",
    "Kluge",
    "Alte",
    "Junge",
    "Flinke",
    "Träge",
    "Warme",
    "Kalte",
    "Reine",
    "Kahle",
    "Reinliche",
    "Ungewaschene",
    "Hübsche",
    "Freundliche",
    "Goldene",
    "Güldene",
    "Eiserne",
    "Runzlige",
    "Langsame",
    "Schnelle",
    "Winzige",
    "Riesige",
    "Edle",
    "Niedere",
    "Einäugige",
    "Leichte",
    "Gute",
    "Bleiche",
    "Braune",
    "Blonde",
    "Graue",
    "Schwierige",
    "Einfache",
    "Schwarze",
    "Plietsche",
    "Begehrte",
    "Gnädige",
    "Rachsüchtige",
    "Eifersüchtige",
    "Harte",
    "Eisenharte",
    "Schlanke",
    "Krumme",
    "Aufrechte",
    "Schelmische",
    "Lustige",
    "Grimmige",
    "Fremde",
    "Picklige",
    "Unbezwingbare",
    "Schläfrige",
    "Freudige",
    "Schlaue",
    "Getriebene",
    "Vertriebene",
    "Verstoßene",
    "Adoptierte",
    "Kranke",
    "Räudige",
    "Wunderbare",
    "Gastfreundliche",
    "Gescheite",
    "Gescheiterte",
    "Sorgsame",
    "Sorgfältige",
    "Sorgenvolle",
    "Gute",
    "Nette",
    "Tollpatschige",
    "Verwachsene",
    "Gesetzlose",
    "Herrische",
    "Gelehrte",
    "Rechtschaffende",
    "Gottesfürchtige",
    "Bibelfeste",
    "Erste",
    "Zweite",
    "Dritte",
    "Vierte",
    "Fünfte",
    "Großzügige",
    "Ungeschickte",
    "Geschickte",
    "Geizige",
    "Scharfsinnige",
    "Glatte",
    "Feine",
    "Grobe",
    "Besorgte",
    "Verarmte",
    "Plumpe",
    "Grobschlächtige"
}

nicknames.noPrefix = {
    "Goldzunge",
    "Goldkehlchen",
    "aus der Fremde",
    "Schnellfinger",
    "Schlangenzunge",
    "Warmherz",
    "Leichtfuß",
    "Langhaar",
    "Goldlocke",
    "von der Wasserburg",
    "vom Walde",
    "vom Meer",
    "Großherz",
    "Hinkebein",
    "Klumpfuß",
    "Lispelzunge",
    "Bierfreund",
    "Plappermaul",
    "Stolperzunge",
    "Köhler",
    "von der Weide",
    "von der Vogelweide",
    "vom Strande",
    "von den Wäldern",
    "aus dem Walde",
    "von der Mühle",
    "Eisenerz",
    "Gutherz",
    "Krähenblick",
    "Pechvogel",
    "von Burgunderlanden",
    "vom Rhein",
    "von der Donau",
    "aus dem Elbtal",
    "von den Bergen",
    "von Holstein",
    "aus Wagrien",
    "aus der Lausitz",
    "von der Hammerburg",
    "von der Siegeburg",
    "aus dem Burgenland",
    "aus dem Frankenland",
    "aus dem Sachsenland",
    "aus Schweden",
    "aus Dänemark",
    "Feldmark",
    "Lehmann",
    "Bohnenstange",
    "Großohr",
    "Großfuß",
    "Einauge",
    "Wohlgestalt",
    "Wohlgenährt",
    "Langfinger",
    "vom See",
    "vom Hügel",
    "Sonnenschein",
    "Bärentöter",
    "Feierbier",
    "Lautenspieler",
    "Flötenspieler",
    "aus dem Tale",
    "vom Berge",
    "Wandervogel",
    "Ungestalt",
    "Löwenherz",
    "Spatzenhirn",
    "Sangesfroh",
    "vom Flusse",
    "vom Bach",
    "vom Fischteich",
    "von der Burg",
    "vom Felde",
    "von der See",
    "vom Lande",
    "von der Insel",
    "von der Brücke",
    "vom Moor",
    "Mövenschrey",
    "Rabenschrey",
    "Goldsack",
    "Immerfroh",
    "Müller",
    "Feistebauch",
    "vom Hofe",
    "Müller",
    "Meier",
    "Schwarzkopf",
    "Blondschopf",
    "Liebeskind",
    "Narrenblut",
    "Gernegroß",
    "Blumenfreund",
    "Weinfreund",
    "das Tier",
    "Wagenschmied",
    "Hasenfuß",
    "Hasenohr",
    "Rehbein",
    "Rehauge",
    "Zitterhand",
    "Scharfauge",
    "Wolfstöter",
    "Hundsohr",
    "Großmaul",
    "Kleinfuß",
    "Großfuß",
    "Frohgemut",
    "Liebherz",
    "Liebegott",
    "Bibeltreu",
    "Hinterlist",
    "Ungelenk",
    "Eisvogel",
    "Schneemann",
    "Kaufmann",
    "vom Pferde",
    "Kutscher",
    "Ferneland",
    "Rebenstock",
    "Steinhack",
    "Waldvogel",
    "Fischer",
    "Feingeist",
    "vom Dorfe",
    "Melker",
    "Schafherz",
    "Tapferherz",
    "bei den Tannen",
    "bei den Eichen",
    "bei den Birken",
    "bei den Steinen",
    "aus dem Norden",
    "aus dem Osten",
    "aus dem Süden",
    "aus dem Westen",
    "Fischzunge",
    "Schweinsteiger",
    "Ferkelwemser",
    "Bruns",
    "Petersen",
    "Clausen",
    "Hansen",
    "Röhrich",
    "Rübennase",
    "vom Deich",
    "Deichgraf",
    "Fleischer",
    "Jäger",
    "Feingeist",
    "Schneider",
    "Obermeier",
    "Hinterhuber",
    "Störtebeker",
    "Schweinehirt",
    "Schafhirt",
    "Totengräber",
    "Küster",
    "Festeburg"
}

return nicknames