local mod = ...



-- Nickname list --------------------------------------------------------------------------------------------------------
-- These are randomly appended to the villager's name


local nickNameFemale = {
    "Schwindlerin",
    "Diebin",
    "Kokette",
    "Hochstaplerin",
    "Schwester",
    "Mutter",
    "Großmutter",
    "Schönheit",
    "Kämpferin",
    "Amme",
    "Dienerin",
    "Hure",
    "Bäuerin",
    "Dichterin",
    "Kirchendienerin",
    "Näherin",
    "Göttin",
    "Räubertochter",
    "Pfaffentochter",
    "Bauerntochter",
    "Wandernde",
    "Predigerin",
    "Nonne",
    "Krähe",
    "Lärche",
    "Nachtigall"
}

local nickNameMale = {
    "Sonderling",
    "Schwindler",
    "Dieb",
    "Frauenheld",
    "Fels",
    "Baum",
    "Schlächter",
    "Knochenbrecher",
    "Hochstapler",
    "Seemann",
    "Kapitän",
    "Bruder",
    "Vater",
    "Großvater",
    "Aufschneider",
    "Gespaltene",
    "Angeber",
    "Kämpfer",
    "Tölpel",
    "Krüppel",
    "Räuber",
    "Henker",
    "Pfaffe",
    "Dichter",
    "Krieger",
    "Kämpfer",
    "Bauernsohn",
    "Pastorensohn",
    "Pastor",
    "Prediger",
    "Wanderer",
    "Bärtige",
    "Mönch",
    "Bär",
    "Hund",
    "Hengst",
    "Schläger",
    "Säufer",
    "Riese"
}

local nickNameCommon = {
    "Tapfere",
    "Furchtlose",
    "Sonderbare",
    "Sonderliche",
    "Schüchterne",
    "Hanebüchene",
    "Ehrliche",
    "Feige",
    "Eloquente",
    "Schmierige",
    "Wohlriechende",
    "Ältere",
    "Jüngere",
    "Fromme",
    "Böse",
    "Verrückte",
    "Stille",
    "Falsche",
    "Laute",
    "Barmherzige",
    "Warmherzige",
    "Neidische",
    "Dunkle",
    "Finstere",
    "Beste",
    "Fiese",
    "Starke",
    "Schwache",
    "Schmutzige",
    "Faule",
    "Fleißige",
    "Geniale",
    "Kleine",
    "Große",
    "Reiche",
    "Lange",
    "Kurze",
    "Schnelle",
    "Dienende",
    "Listige",
    "Verwegene",
    "Traurige",
    "Rastlose",
    "Geplagte",
    "Bucklige",
    "Dumme",
    "Dumpfe",
    "Glückliche",
    "Einfältige",
    "Niederträchtige",
    "Fette",
    "Feiste",
    "Dünne",
    "Dürre",
    "Taube",
    "Blinde",
    "Käufliche",
    "Erhabene",
    "Kluge",
    "Alte",
    "Junge",
    "Flinke",
    "Träge",
    "Warme",
    "Kalte",
    "Reine",
    "Reinliche",
    "Stinkende",
    "Ungewaschene",
    "Hübsche",
    "Freundliche",
    "Goldene",
    "Güldene",
    "Eiserne",
    "Runzlige",
    "Langsame",
    "Schnelle",
    "Winzige",
    "Riesige",
    "Edle",
    "Niedere",
    "Einäugige",
    "Leichte",
    "Gute",
    "Bleiche",
    "Braune",
    "Blonde",
    "Graue",
    "Schwierige",
    "Einfache",
    "Schwarze",
    "Plietsche",
    "Begehrte",  
    "Begehrende",
    "Gnädige",
    "Rachsüchtige",
    "Eifersüchtige",
    "Eisenharte",
    "Frömmelnde",
    "Schlanke",
    "Krumme",
    "Aufrechte",
    "Aufopfernde",
    "Hinkende",
    "Stotternde",
    "Tanzende",
    "Schelmische",
    "Lustige",
    "Grimmige",
    "Fremde",
    "Picklige",
    "Unbezwingbare",
    "Schläfrige",
    "Freudige",
    "Schlaue",
    "Getriebene",
    "Vertriebene",
    "Verstoßene",
    "Adoptierte",
    "Kranke",
    "Räudige",
    "Wunderbare",
    "Gastfreundliche",
    "Gescheite",
    "Gescheiterte",
    "Sorgsame",
    "Sorgfältige",
    "Gute",
    "Nette",
    "Tollpatschige",
    "Verwachsene",
    "Gesetzlose",
    "Herrische",
    "Gelehrte",
    "Rechtschaffende",
    "Erste",
    "Zweite",
    "Dritte",
    "Vierte",
    "Fünfte",
    "Großzügige",
    "Geizige",
    "Scharfsinnige",
    "Glatte",
    "Feine",
    "Grobe",
    "Grobschlächtige"
}


local nickNameNoPrefix = {
    "Goldzunge",
    "Goldkehlchen",
    "aus der Fremde",
    "Schnellfinger",
    "Schlangenzunge",
    "Warmherz",
    "Leichtfuß",
    "Langhaar",
    "Goldlocke",
    "von der Wasserburg",
    "vom Walde",
    "vom Meer",
    "Großherz",
    "Hinkebein",
    "Lispelzunge",
    "Bierfreund",
    "Plappermaul",
    "Köhler",
    "von der Weide",
    "von der Vogelweide",
    "vom Strande",
    "von den Wäldern",
    "Gutherz",
    "Krähenblick",
    "Pechvogel",
    "von Burgunderschink",
    "von den Bergen",
    "Bohnenstange",
    "Großohr",
    "Großfuß",
    "Einauge",
    "Wohlgestalt",
    "Wohlgenährt",
    "Langfinger",
    "vom See",
    "vom Hügel",
    "Sonnenschein",
    "Bärentöter",
    "Feierbier",
    "Lautenspieler",
    "Flötenspieler",
    "aus dem Tale",
    "vom Berge",
    "Wandervogel",
    "Ungestalt",
    "Sangesfroh",
    "vom Flusse",
    "vom Bach",
    "vom Fischteich",
    "von der Burg",
    "vom Felde",
    "von der See",
    "vom Lande",
    "von der Insel",
    "vom Moor",
    "Mövenschiet",
    "Goldsack",
    "Immerfroh",
    "Müller",
    "Feistebauch",
    "vom Hofe",
    "Müller",
    "Meier",
    "Schwarzkopf",
    "Blondschopf",
    "Liebeskind",
    "Dummkopf",
    "Gernegroß",
    "Blumenfreund",
    "Weinfreund",
    "das Tier",
    "Wagenschmied",
    "Zitterhand",
    "Scharfauge",
    "Wolfstöter",
    "Hundefreund",
    "Großmaul",
    "Kleinfuß",
    "Großfuß",
    "Frohgemut",
    "Liebherz",
    "Liebegott",
    "Bibeltreu",
    "Hinterlist",
    "Ungelenk",
    "Eisvogel",
    "Schneemann",
    "Kaufmann",
    "vom Pferde",
    "Kutscher",
    "Steinhack",
    "Waldvogel",
    "Fischer",
    "Feingeist",
    "vom Dorfe",
    "Melker",
    "Schafherz",
    "Tapferherz",
    "bei den Tannen",
    "bei den Eichen",
    "bei den Birken",
    "bei den Steinen",
    "aus dem Norden",
    "aus dem Osten",
    "aus dem Süden",
    "aus dem Westen",
    "Fischzunge",
    "Schweinsteiger",
    "Ferkelwemser",
    "Bruns",
    "Petersen",
    "Clausen",
    "Hansen",
    "Röhrich",
    "Rübennase",
    "vom Deich",
    "Deichgraf",
    "Fleischer",
    "Jäger",
    "Feingeist",
    "Schneider",
    "Obermeier",
    "Hinterhuber",
    "Schweinehirt",
    "Schafhirt",
    "Totengräber",
    "Küster"
}



-- Male Name list --------------------------------------------------------------------------------------------------------
local maleName = {
    "Adam",
    "Albert",
    "Adrian",
    "Ansgar",
    "Arnold",
    "Arnhold",
    "Arnulf",
    "Arno",
    "Andi",
    "Andreas",
    "Alex",
    "Alexander",
    "Alfons",
    "Adalbert",
    "Adolf",
    "Adur",
    "Ansgar",
    "Alwin",
    "Alois",
    "Arne",
    "Astor",
    "Axel",
    "August",
    "Augustin",
    "Anton",
    "Armin",
    "Balduin",
    "Bert",
    "Berti",
    "Bruno",
    "Ben",
    "Benno",
    "Bent",
    "Benedikt",
    "Benjamin",
    "Benni",
    "Bernhard",
    "Balthasar",
    "Bernd",
    "Berthold",
    "Björn",
    "Boris",
    "Baldur",
    "Baldwin",
    "Bertram",
    "Burkhard",
    "Bjarne",
    "Christian",
    "Christoph",
    "Caspar",
    "Carsten",
    "Constantin",
    "Caius",
    "Carl",
    "David",
    "Dagobert",
    "Dalvin",
    "Dieter",
    "Dietmar",
    "Dietrich",
    "Dominik",
    "Daniel",
    "Dirk",
    "Elias",
    "Elian",
    "Enno",
    "Emil",
    "Enrik",
    "Erik",
    "Elmar",
    "Edo",
    "Eduard",
    "Edward",
    "Egon",
    "Enrico",
    "Eckart",
    "Eike",
    "Ernst",
    "Fred",
    "Filip",
    "Flip",
    "Finn",
    "Falk",
    "Felix",
    "Ferdinand",
    "Fridolin",
    "Frowald",
    "Gert",
    "Götz",
    "Gerhard",
    "Gerold",
    "Gustav",
    "Günther",
    "Gunter",
    "Günter",
    "Gernot",
    "Grimbald",
    "Grünwald",
    "Gotthilf",
    "Gotthold",
    "Gottwald",
    "Gandolf",
    "Hanno",
    "Hein",
    "Hagen",
    "Heinz",
    "Heini",
    "Heiner",
    "Heimfried",
    "Heinrich",
    "Hinrich",
    "Horst",
    "Herbert",
    "Heribert",
    "Hilbert",
    "Hubert",
    "Hinnerk",
    "Helmut",
    "Ide",
    "Isger",
    "Immanuel",
    "Ingmar",
    "Jochen",
    "Jockel",
    "Jos",
    "Joachim",
    "Jens",
    "Jakob",
    "Jörg",
    "Kurt",
    "Kuno",
    "Kris",
    "Kalle",
    "Krischan",
    "Karl",
    "Karl-Heinz",
    "Klaus",
    "Klaus-Dieter",
    "Klaus-Peter",
    "Kai",
    "Knut",
    "Ludwig",
    "Lorenz",
    "Lars",
    "Lemmy",
    "Leif",
    "Leonhard",
    "Lutz",
    "Menno",
    "Meinhard",
    "Meinolf",
    "Manfred",
    "Moritz",
    "Morten",
    "Matthias",
    "Markus",
    "Marcus",
    "Matze",
    "Martin",
    "Max",
    "Maximilian",
    "Norbert",
    "Noah",
    "Oliver",
    "Ole",
    "Oskar",
    "Oscar",
    "Ottmar",
    "Otto",
    "Onno",
    "Odin",
    "Ottfried",
    "Olaf",
    "Paul",
    "Peter",
    "Pit",
    "Philip",
    "Rainer",
    "Reinhard",
    "Ronno",
    "Rudolf",
    "Rudi",
    "Robert",
    "Roland",
    "Ronald",
    "Rupert",
    "Rollo",
    "Ruprecht",
    "Ralf",
    "Rupert",
    "Siegfried",
    "Siegmund",
    "Stephan",
    "Stefan",
    "Sascha",
    "Sven",
    "Torsten",
    "Theo",
    "Theoderich",
    "Theobald",
    "Tim",
    "Timo",
    "Temmo",
    "Thor",
    "Thies",
    "Tilo",
    "Thaddäus",
    "Ulf",
    "Ulfred",
    "Ulrich",
    "Urs",
    "Udo",
    "Victor",
    "Vincent",
    "Vincenz",
    "Volker",
    "Volkwin",
    "Walter",
    "Waldemar",
    "Werner",
    "Wieland",
    "Wolfram",
    "Wolfgang",
    "Wilhelm",
    "Willi",
    "Wulf",
    "Wollo",
    "Wilbert",
    "Yannis",
    "Xaver"
}



-- Female Name list --------------------------------------------------------------------------------------------------------
local femaleName = {
   "Adele",
   "Adelheid",
   "Anna",
   "Anne",
   "Annfried",
   "Annelinde",
   "Andrea",
   "Adriana",
   "Adele",
   "Agnes",
   "Alberta",
   "Almut",
   "Aloisa",
   "Amelie",
   "Angela",
   "Angelika",
   "Arwen",
   "Arlene",
   "Anja",
   "Adelma",
   "Almut",
   "Annika",
   "Amalie",
   "Amalia",
   "Annegret",
   "Alice",
   "Alwina",
   "Amira",
   "Annemarie",
   "Antonia",
   "Antje",
   "Anabel",
   "Alina",
   "Ann",
   "Britta",
   "Bärbel",
   "Beate",
   "Birte",
   "Breanna",
   "Brigitte",
   "Berta",
   "Brunhilde",
   "Cäcilie",
   "Christiane",
   "Christa",
   "Claudia",
   "Charlotte",
   "Clementine",
   "Dietline",
   "Diane",
   "Dorothea",
   "Deike",
   "Dora",
   "Dolores",
   "Eleonore",
   "Edeltraud",
   "Elfriede",
   "Erna",
   "Eila",
   "Elke",
   "Emma",
   "Else",
   "Edda",
   "Elsa",
   "Emmeline",
   "Ernestine",
   "Erika",
   "Emmi",
   "Elli",
   "Enna",
   "Eva",
   "Edelgard",
   "Frauke",
   "Frigga",
   "Fara",
   "Freya",
   "Fenja",
   "Franka",
   "Franziska",
   "Frida",
   "Friderike",
   "Gesa",
   "Grete",
   "Greta",
   "Gundula",
   "Gerlinde",
   "Gerda",
   "Gertrud",
   "Gesa",
   "Gudrun",
   "Hedda",
   "Hella",
   "Hilde",
   "Hanna",
   "Hemma",
   "Henriette",
   "Henrieke",
   "Heilrun",
   "Hermine",
   "Heike",
   "Heide",
   "Heidi",
   "Heidrun",
   "Ida",
   "Imke",
   "Ina",
   "Isabel",
   "Isabella",
   "Inge",
   "Ingeborg",
   "Iris",
   "Ingrid",
   "Janina",
   "Jette",
   "Josepha",
   "Josephina",
   "Jana",
   "Johanna",
   "Karla",
   "Klara",
   "Karlotta",
   "Karolina",
   "Kunigunde",
   "Krista",
   "Katharina",
   "Lina",
   "Lotte",
   "Lilli",
   "Luise",
   "Lisa",
   "Lieselotte",
   "Meike",
   "Mareike",
   "Melinda",
   "Mathilda",
   "Maria",
   "Marianne",
   "Merlinde",
   "Martha",
   "Minna",
   "Magda",
   "Meta",
   "Nina",
   "Ottilde",
   "Ottilia",
   "Olga",
   "Olivia",
   "Ophelia",
   "Petra",
   "Paula",
   "Penelope",
   "Paulina",
   "Patricia",
   "Rena",
   "Renate",
   "Ronja",
   "Rosa",
   "Rosalinde",
   "Rosamunde",
   "Roswita",
   "Ramona",
   "Rebecca",
   "Ruth",
   "Rosalie",
   "Romilda",
   "Sabine",
   "Susanne",
   "Solveig",
   "Sieglinde",
   "Sigune",
   "Svea",
   "Senta",
   "Svenja",
   "Thekla",
   "Theodora",
   "Theresa",
   "Thialda",
   "Tanja",
   "Tina",
   "Tilda",
   "Thea",
   "Tatjana",
   "Tamina",
   "Ute",
   "Uta",
   "Ulla",
   "Undine",
   "Ursula",
   "Ulrike",
   "Victoria",
   "Wilma",
   "Wencke",
   "Wanda",
   "Wiebke",
   "Wilhelmine",
   "Waltraud",
   "Walpurga"
}

local function combineArrays(arrayone, arraytwo,prefix)
    local combinedArray = {}
    for i = 1, #arrayone do
      table.insert(combinedArray, prefix .. " " .. arrayone[i])
    end
    for i = 1, #arraytwo do
      table.insert(combinedArray, prefix .. " " .. arraytwo[i])
    end
    for i = 1, #nickNameNoPrefix do
        table.insert(combinedArray, nickNameNoPrefix[i])
    end
      
    return combinedArray
  end

-- Append nicknames to names randomly ---------------------------------------------------------------------------

local nickNameF = combineArrays(nickNameFemale,nickNameCommon,"die")
local nickNameM = combineArrays(nickNameMale,nickNameCommon,"der")
local maleNames = {}
local femaleNames = {}

for i = 1, 5000 do
    local rand1 = math.random(#nickNameM)
    local rand2 = math.random(#maleName)
    table.insert(maleNames, maleName[rand2] .. " " .. nickNameM[rand1])
end

for i = 1, 5000 do
    local rand1 = math.random(#nickNameF)
    local rand2 = math.random(#femaleName)
    table.insert(femaleNames, femaleName[rand2] .. " " .. nickNameF[rand1])
end


-- Override name list ---------------------------------------------------------------------------
 mod:overrideAsset({
    Id = "NAME_LIST_ENGLISH",
    MaleNameList = maleNames,
    FemaleNameList = femaleNames,
})

